[project]
name = "voxelcity"
version = "0.1.78"
requires-python = ">=3.10,<3.13"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
description = "voxelcity is an easy and one-stop tool to output 3d city models for microclimate simulation by integrating multiple geospatial open-data"
readme = "README.md"
authors = [
  {name = "Kunihiko Fujiwara", email = "kunihiko@nus.edu.sg"}
]
maintainers = [
  {name = "Kunihiko Fujiwara", email = "kunihiko@nus.edu.sg"}
]
license = {text = "MIT"}
dependencies = [
    "typer",
    "pandas",
    "requests",
    "pyproj",
    "ipyleaflet",
    "geopandas",
    "rasterio==1.3.11",
    "shapely",
    "gdown",
    "numpy",
    "matplotlib",
    "contextily",
    "fiona",
    "rtree",
    "plotly",
    "tqdm",
    "scipy",
    "affine",
    "earthengine-api",
    "geemap",
    "rio-cogeo",
    "geopy",
    "py-vox-io",
    "mapbox_vector_tile",
    "numba",
    "reverse_geocoder",
    "pycountry",
    "osm2geojson",
    "seaborn",
    "overturemaps",
    "protobuf==3.20.3",
    "timezonefinder"
]

[project.scripts]
voxelcity = "voxelcity.cli:main"

[project.optional-dependencies]
dev = [
    "coverage",
    "mypy",
    "pytest",
    "ruff"
]

[project.urls]
bugs = "https://github.com/kunifujiwara/voxelcity/issues"
changelog = "https://github.com/kunifujiwara/voxelcity/blob/master/changelog.md"
homepage = "https://github.com/kunifujiwara/voxelcity"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["voxelcity", "voxelcity.download", "voxelcity.geo", "voxelcity.file", "voxelcity.sim", "voxelcity.utils"]

[tool.setuptools.package-data]
"*" = ["*.*"]

[tool.mypy]
files = "."
strict = true
warn_unreachable = true
warn_no_return = true

[[tool.mypy.overrides]]
module = "tests.*"
allow_untyped_defs = true
disable_error_code = "attr-defined"