[project]
name = "AFS_file_validator"
version = "1.1.4"
description = "测试AFS文件签名"
authors = [
    { name = "funcdefmain", email = "741132517@qq.com" },
]
dependencies = [
    "pefile>=2023.2.7",
    "tqdm>=4.66.4",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
