[project]
name = "imageboard"
version = "0.3.1"
description = "imageboard is a simple image display tool. Aim to provide a simple way to share experimental results."
readme = "README.md"
authors = [{ name = "Jianqi Pan", email = "jannchie@gmail.com" }]
requires-python = ">=3.10"
dependencies = ["matplotlib>=3.9.3", "pillow>=11.0.0", "pydantic>=2.10.3"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]


[tool.ruff]
select = ["ALL"]
exclude = ["alembic"]
ignore = [
    "PGH",
    "RUF003",
    "BLE001",
    "ERA001",
    "FIX002",
    "TD002",
    "TD003",
    "A004",
    "ANN201",
    "B008",
    "FAST002",
]
line-length = 120

[tool.uv]
package = true
