[project]
name = "dln-api"
version = "0.1.1"
dynamic = ["dependencies"]
description = "DLN API package"
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "BSD License" }
authors = [{ name = "Guillaume Sottas", email = "guillaumesottas@gmail.com" }]
urls = { "Repository" = "https://github.com/Sauci/dln-api" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix"
]

[build-system]
requires = [
    "setuptools>=61",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = [
    "dln_api",
    "dln_api.spi_master",
    "dln_api.spi_slave"
]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }


[project.scripts]
uhil-api-server = "server.cli:main"
