[project]
name = "whiteduck"
version = "0.4.5"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andre Ratzenberger", email = "andre.ratzenberger@whiteduck.de" }
]
requires-python = ">=3.10"
dependencies = [
    "rich>=13.9.4",
    "typer>=0.15.1",
]

[project.scripts]
whiteduck = "whiteduck:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
