[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mqtt_backend_serrawatch"]

[project]
name = "mqtt_backend_serrawatch"
version = "0.2.13"
authors = [
  { name="Alexandre Grzegorczyk", email="alexandregrzegorczyk2@gmail.com" },
]
description = "This project was created as part of the Internet of Things (IoT) course in the Master's program in Computer Architecture at the Haute École de la Province de Liège (HEPL)."
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/IOTSerraWatch/Client_OnUbuntu"
Issues = "https://github.com/IOTSerraWatch/Client_OnUbuntu/issues"
