[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyrotkit"
version = "0.0.3"
authors = [
    {name="J&S Games", email="ideal.job6119@fastmail.com"}
]
description = "A library to help with roguelikes"
readme= "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=2.2"
]

[project.urls]
Homepage = "https://github.com/elegantiron/pyrotkit"
Issues = "https://github.com/elegantiron/pyrotkit/issues"