[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "influencemapper"
description = "A tool for extracting information from disclosure statements."
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"
keywords = ["disclosure", "conflict of interests", "competing interest", "research"]
authors = [{name="Hardy", email="hardy.oei@gmail.com"}]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
  "Topic :: Scientific/Engineering :: Information Analysis",
]
dependencies = [
  "attrs==24.2.0",
  "beautifulsoup4==4.12.3",
  "jupyterlab==4.2.5",
  "fuzzywuzzy==0.18.0",
  "lxml==5.3.0",
  "nltk==3.9.1",
  "openai==1.55.3",
  "pandas==1.5.3",
  "pydantic==2.8.2",
  "spacy==3.7.6",
  "tiktoken==0.7.0",
  "tqdm==4.66.5",
  "python-Levenshtein==0.26.1",
  "httpx==0.27.2"
]
version = "0.9.2"

[tool.hatch.build.targets.wheel]
packages = ["core/src/influencemapper"]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"