[project]
name = "nonebot-plugin-ollama"
version = "0.2.1"
description = "通过ollama提供的接口， 将你的nonebot连接到本地部署的基于ollama框架的LLM模型。"
authors = [
    { name = "MaStAr", email = "2024381053@mails.szu.edu.cn" },
]
dependencies = [
    "requests>=2.32.3",
    "nb-cli>=1.4.2",
    "nonebot2>=2.4.0",
]
requires-python = ">=3.9"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.package]
include = [
    "src/**/*",
    "LICENSE",
    "README.md",
]
exclude = [
    "tests/**/*",
    "dist/",
]

[dependency-groups]
dev = [
    "twine>=6.0.1",
]
