[providers]
names = ['openai', 'moon', 'qwen', 'zhipu', 'yi', 'step', 'azure', 'intern', 'ollama', 'deepseek', 'groq', 'openrouter', 'sambanova', 'tencent']

[openai]
doc_url = 'https://platform.openai.com/docs/overview'
models = ['gpt-4o', 'gpt-4o-mini', 'o1-preview', 'o1-mini']
pricing = [2.5, 0.15, 15.0, 3.0] #1M USD
embeddings = ['text-embedding-3-small', 'text-embedding-3-large']
model_name = "gpt-3.5-turbo"
temperature = 0.7
max_tokens = 2000

[moon]
doc_url = 'https://platform.moonshot.cn/docs'
models = ['moonshot-v1-auto', 'moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k']
pricing = [12, 12, 24, 60]
base_url = 'https://api.moonshot.cn/v1'

[qwen]
doc_url = 'https://help.aliyun.com/zh/dashscope/?spm=a2c4g.11186623.0.0.4780fa701KqDuP'
models = ['qwen-max', 'qwen-max-longcontext', 'qwen-vl-max', 'qwen-vl-plus', 'qwen2-72b-instruct', 'qwen1.5-72b-chat']
embeddings = ['text-embedding-v2']
base_url = 'https://dashscope.aliyuncs.com/compatible-mode/v1'

[zhipu]
models = ['glm-4-plus', 'glm-4-0520', 'glm-4-airx', 'glm-4-air', 'glm-4-long', 'glm-4-flashx', 'glm-4-flash']
pricing = [50.0, 100.0, 10.0, 1.0, 1.0, 1.0, 0.1]
embeddings = ['embedding-2']
base_url = 'https://open.bigmodel.cn/api/paas/v4/'
doc_url = 'https://maas.aminer.cn/dev/api'
pricing_doc_url = 'https://open.bigmodel.cn/pricing'


[yi]
doc_url = 'https://platform.lingyiwanwu.com/docs'
models = ['yi-lightning', 'yi-large', 'yi-large-rag', 'yi-large-turbo', 'yi-vision', 'yi-medium']
pricing = [0.99, 20.0, 25.0, 12.0, 6.0, 2.5] #1M
base_url = 'https://api.lingyiwanwu.com/v1'
pricing_doc_url = 'https://platform.lingyiwanwu.com/docs#%E6%A8%A1%E5%9E%8B%E4%B8%8E%E8%AE%A1%E8%B4%B9'

[deepseek]
# support name in message
doc_url = 'https://platform.deepseek.com/api-docs/zh-cn/'
models = ['deepseek-chat']
pricing = [1]
base_url = 'https://api.deepseek.com'

[grok]
doc_url='https://docs.x.ai/docs'
models = ['grok-beta']
base_url='https://api.x.ai/v1'

[silicon]
doc_url = 'https://docs.siliconflow.cn/docs/getting-started'
models = ['Qwen/Qwen2.5-72B-Instruct','Qwen/Qwen2.5-72B-Instruct-128K', 'google/gemma-2-27b-it', 'deepseek-ai/DeepSeek-V2-Chat', '01-ai/Yi-1.5-34B-Chat-16K', 'deepseek-ai/DeepSeek-V2-Chat']
pricing=[4.13,4.13]
embeddings = ['netease-youdao/bce-embedding-base_v1']
reranker=['netease-youdao/bce-reranker-base_v1','BAAI/bge-reranker-v2-m3']
base_url = 'https://api.siliconflow.cn/v1'

[step]
doc_url = 'https://platform.stepfun.com/docs/overview/concept'
models = ['step-2-16k','step-1-8k', 'step-1v-8k', 'step-1v-32k', 'step-1-32k', 'step-1-128k', 'step-256k']
pricing=[38,5,5,15,15,40,95]
base_url = "https://api.stepfun.com/v1"

[azure]
doc_url = ''
models = ['gpt4o']
embeddings = ['textembedding3small']
api_version = '2024-02-15-preview'
base_url = 'https://pygaiservice.openai.azure.com/'

[intern]
doc_url = 'https://internlm.intern-ai.org.cn/api/document'
models = ['internlm2.5-latest']
base_url = "https://internlm-chat.intern-ai.org.cn/puyu/api/v1/"

[ollama]
doc_url = 'https://internlm.intern-ai.org.cn/api/document'
models = ['qwen:14b-chat', 'qwen2:7b-instruct-q8_0', 'gemma2:9b-instruct-q8_0']
base_url = "http://localhost:11434/v1"


[groq]
models = ['llama-3.1-70b-versatile', 'llama-3.1-8b-instant', 'gemma2-9b-it']
audio = ['whisper-large-v3']
doc_url = 'https://console.groq.com/docs/'
base_url = 'http://chat.bluemeat.work:8099/groq/v1'

[openrouter]
models = ['meta-llama/llama-3.1-8b-instruct:free', 'qwen/qwen-2-7b-instruct:free', 'openai/gpt-4o-mini', 'meta-llama/llama-3.1-70b-instruct', 'meta-llama/llama-3.1-405b-instruct']
doc_url = 'https://openrouter.ai/docs'
base_url = "https://openrouter.ai/api/v1"

[deepbricks]
models = ['GPT-4o-mini', 'GPT-4o', 'Claude-3.5-Sonnet']
doc_url = 'https://deepbricks.ai/docs'
base_url = 'https://api.deepbricks.ai/v1'

[sambanova]
models = ['Meta-Llama-3.1-405B-Instruct']
doc_url = 'https://cloud.sambanova.ai/apis'
base_url = 'https://api.sambanova.ai/v1'

[tencent]
models = ['hunyuan-pro', 'hunyuan-turbo-latest', 'hunyuan-standard-256K', 'hunyuan-standard', 'hunyuan-lite', 'hunyuan-functioncall']
doc_url = 'https://cloud.tencent.com/document/product/1729/104753'
base_url = 'https://api.hunyuan.cloud.tencent.com/v1'

[anthropic]
model_name = "claude-3-sonnet-20240229"
temperature = 0.7
max_tokens = 2000