[tool.poetry]
name = "sgfixedincome_pkg"
version = "0.1.9"
description = "A package to aggregate fixed income products available to Singapore residents to earn yield on singapore dollars"
authors = ["Gideon Tay"]
license = "MIT"
readme = "README.md"
documentation = 'https://sgfixedincome-pkg.readthedocs.io/en/latest/'
homepage = "https://github.com/GidTay/sgfixedincome_pkg"
repository = "https://github.com/GidTay/sgfixedincome_pkg"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
beautifulsoup4 = "^4.12.3"
pandas = "^2.2.3"
matplotlib = "^3.9.3"
seaborn = "^0.13.2"
numpy = "^2.2.0"
pytz = "^2024.2"
streamlit = "^1.41.0"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-cov = "^6.0.0"
pytest-mock = "^3.14.0"
myst-nb = "^1.1.2"
sphinx-autoapi = "^3.4.0"
sphinx-rtd-theme = "^3.0.2"
ipykernel = "^6.29.5"
jupyter = "^1.1.1"
codecov = "^2.1.13"

[tool.poetry.scripts]
sgfixedincome-app = "sgfixedincome_pkg.cli:run_app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"