# Python package
# This file defines this Python package.
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

[build-system]
requires = ["setuptools >= 75.0"]
build-backend = "setuptools.build_meta"

[project]
name = "secret-duck"
description = "MQTT listener to save data"
readme = "README.md"
# https://packaging.python.org/en/latest/discussions/versioning/
version = "0.0.4"
dependencies = [
    "pykeepass==4.*"
]
# https://devguide.python.org/versions/
requires-python = ">= 3.9"
authors = [
    { name = "Joe Heffer", email = "j.heffer@sheffield.ac.uk" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#creating-executable-scripts
[project.scripts]
secret-duck = "secret_duck.__main__:main"

[project.optional-dependencies]
test = [
    "pytest",
    "flake8",
    "black"
]

[project.urls]
Homepage = "https://pypi.org/p/secret-duck"
Repository = "https://github.com/CUREd-Plus/secret-duck"
Issues = "https://github.com/CUREd-Plus/secret-duck/issues"
Changelog = "https://github.com/CUREd-Plus/secret-duck/releases"
