[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "django-channels-chat"
version = "0.6"
# dependencies = [
#     "django>=2.2.8",  # Replace "X.Y" as appropriate
#     "channels>=3.0.4",
#     "channels-redis>=3.3.1",
#     "daphne>=3.0.2",
# ]
dependencies = []
description = "A basic example of a Chat made with Django Channels"
readme = "README.md"
requires-python = ">= 3.9"
authors = [
    {name = "Luis Salgado", email = "luisabraham102@gmail.com"},
]
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 2.2",  # Replace "X.Y" as appropriate
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]

[project.urls]
Homepage = "https://www.example.com/"