[package]
name = "meme_generator"
description = "Meme generator for making fun pictures"
version.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
ctor = "0.2"
directories = "5.0"
gif = "0.13"
image = "0.25"
indicatif = "0.16"
qrcode = "0.14"
rand = "0.8"
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9"
skia-safe = { version = "0.80", features = ["textlayout"] }
tokio = { version = "1.42", features = ["full"] }
toml = "0.8"

meme_options_derive = { version = "0.0.2", path = "../meme_options_derive" }

[features]
contrib = []
