[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "erf-gui"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "John Fiocca", email = "void@some.where" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "pandas",
]

[project.urls]
Documentation = "https://github.com/John Fiocca/erf-gui#readme"
Issues = "https://github.com/John Fiocca/erf-gui/issues"
Source = "https://github.com/John Fiocca/erf-gui"

[project.scripts]
erf-gui = "erf_gui.cli:create_gui"

[tool.hatch.version]
path = "src/erf_gui/__about__.py"

[tool.hatch.envs.erf-gui]
python = "3.12"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/erf_gui tests}"

[tool.coverage.run]
source_pkgs = ["erf_gui", "tests"]
branch = true
parallel = true
omit = [
  "src/erf_gui/__about__.py",
]

[tool.coverage.paths]
erf_gui = ["src/erf_gui", "*/erf-gui/src/erf_gui"]
tests = ["tests", "*/erf-gui/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
