[build-system]
requires = ["hatchling", "requests"]
build-backend = "hatchling.build"

[project]
name = "veracross_api3"
version = "0.0.3"
authors = [
  { name="Forrest Beck", email="forrest.beck@gmail.com" },
]
description = "Simple library for interacting with the Veracross API"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/beckf/veracross_api3/"
Issues = "https://github.com/beckf/veracross_api3/issues"