[project]
name = "tpf"
version = "1.0.23"
authors = [
  { name="Prentice Qisan", email="itoracle@163.com" },
]
description = "AI Common Methods Set"
dependencies = [
  "cx_Oracle",
  "pymysql==1.0.2"
]

readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
Homepage = "https://gitee.com/star-spinning/tpf"
Issues = "https://gitee.com/star-spinning/tpf/issues"